// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: backup.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Update strategy enum.
type UpdateStrategy int32

const (
	UpdateStrategy_ALWAYS_UPDATE   UpdateStrategy = 0
	UpdateStrategy_ONLY_FETCH_ONCE UpdateStrategy = 1
)

// Enum value maps for UpdateStrategy.
var (
	UpdateStrategy_name = map[int32]string{
		0: "ALWAYS_UPDATE",
		1: "ONLY_FETCH_ONCE",
	}
	UpdateStrategy_value = map[string]int32{
		"ALWAYS_UPDATE":   0,
		"ONLY_FETCH_ONCE": 1,
	}
)

func (x UpdateStrategy) Enum() *UpdateStrategy {
	p := new(UpdateStrategy)
	*p = x
	return p
}

func (x UpdateStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_backup_proto_enumTypes[0].Descriptor()
}

func (UpdateStrategy) Type() protoreflect.EnumType {
	return &file_backup_proto_enumTypes[0]
}

func (x UpdateStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UpdateStrategy) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UpdateStrategy(num)
	return nil
}

// Deprecated: Use UpdateStrategy.Descriptor instead.
func (UpdateStrategy) EnumDescriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{0}
}

// Top-level backup container.
// Field numbers must match Komikku's @ProtoNumber annotations exactly.
type Backup struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BackupManga      []*BackupManga         `protobuf:"bytes,1,rep,name=backup_manga,json=backupManga" json:"backup_manga,omitempty"`
	BackupCategories []*BackupCategory      `protobuf:"bytes,2,rep,name=backup_categories,json=backupCategories" json:"backup_categories,omitempty"`
	// Field 100 was legacy broken sources (skipped)
	BackupSources           []*BackupSource            `protobuf:"bytes,101,rep,name=backup_sources,json=backupSources" json:"backup_sources,omitempty"`
	BackupPreferences       []*BackupPreference        `protobuf:"bytes,104,rep,name=backup_preferences,json=backupPreferences" json:"backup_preferences,omitempty"`
	BackupSourcePreferences []*BackupSourcePreferences `protobuf:"bytes,105,rep,name=backup_source_preferences,json=backupSourcePreferences" json:"backup_source_preferences,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Backup) Reset() {
	*x = Backup{}
	mi := &file_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backup) ProtoMessage() {}

func (x *Backup) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backup.ProtoReflect.Descriptor instead.
func (*Backup) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{0}
}

func (x *Backup) GetBackupManga() []*BackupManga {
	if x != nil {
		return x.BackupManga
	}
	return nil
}

func (x *Backup) GetBackupCategories() []*BackupCategory {
	if x != nil {
		return x.BackupCategories
	}
	return nil
}

func (x *Backup) GetBackupSources() []*BackupSource {
	if x != nil {
		return x.BackupSources
	}
	return nil
}

func (x *Backup) GetBackupPreferences() []*BackupPreference {
	if x != nil {
		return x.BackupPreferences
	}
	return nil
}

func (x *Backup) GetBackupSourcePreferences() []*BackupSourcePreferences {
	if x != nil {
		return x.BackupSourcePreferences
	}
	return nil
}

// A single manga entry with all associated data embedded inline.
type BackupManga struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Source       *int64                 `protobuf:"varint,1,req,name=source" json:"source,omitempty"`
	Url          *string                `protobuf:"bytes,2,req,name=url" json:"url,omitempty"`
	Title        *string                `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Artist       *string                `protobuf:"bytes,4,opt,name=artist" json:"artist,omitempty"`
	Author       *string                `protobuf:"bytes,5,opt,name=author" json:"author,omitempty"`
	Description  *string                `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	Genre        []string               `protobuf:"bytes,7,rep,name=genre" json:"genre,omitempty"`
	Status       *int32                 `protobuf:"varint,8,opt,name=status" json:"status,omitempty"`
	ThumbnailUrl *string                `protobuf:"bytes,9,opt,name=thumbnail_url,json=thumbnailUrl" json:"thumbnail_url,omitempty"`
	// 10 = customCover (1.x, unused)
	// 11 = lastUpdate (1.x, unused)
	// 12 = lastInit (1.x, unused)
	DateAdded *int64 `protobuf:"varint,13,opt,name=date_added,json=dateAdded" json:"date_added,omitempty"`
	Viewer    *int32 `protobuf:"varint,14,opt,name=viewer" json:"viewer,omitempty"`
	// 15 = flags (1.x, unused)
	Chapters   []*BackupChapter  `protobuf:"bytes,16,rep,name=chapters" json:"chapters,omitempty"`
	Categories []int64           `protobuf:"varint,17,rep,name=categories" json:"categories,omitempty"`
	Tracking   []*BackupTracking `protobuf:"bytes,18,rep,name=tracking" json:"tracking,omitempty"`
	// Values not in 1.x but used in 0.x (bumped by 100)
	Favorite     *bool  `protobuf:"varint,100,opt,name=favorite" json:"favorite,omitempty"`
	ChapterFlags *int32 `protobuf:"varint,101,opt,name=chapter_flags,json=chapterFlags" json:"chapter_flags,omitempty"`
	// 102 = broken history (legacy)
	ViewerFlags        *int32           `protobuf:"varint,103,opt,name=viewer_flags,json=viewerFlags" json:"viewer_flags,omitempty"`
	History            []*BackupHistory `protobuf:"bytes,104,rep,name=history" json:"history,omitempty"`
	UpdateStrategy     *UpdateStrategy  `protobuf:"varint,105,opt,name=update_strategy,json=updateStrategy,enum=tachibk.UpdateStrategy" json:"update_strategy,omitempty"`
	LastModifiedAt     *int64           `protobuf:"varint,106,opt,name=last_modified_at,json=lastModifiedAt" json:"last_modified_at,omitempty"`
	FavoriteModifiedAt *int64           `protobuf:"varint,107,opt,name=favorite_modified_at,json=favoriteModifiedAt" json:"favorite_modified_at,omitempty"`
	ExcludedScanlators []string         `protobuf:"bytes,108,rep,name=excluded_scanlators,json=excludedScanlators" json:"excluded_scanlators,omitempty"`
	Version            *int64           `protobuf:"varint,109,opt,name=version" json:"version,omitempty"`
	Notes              *string          `protobuf:"bytes,110,opt,name=notes" json:"notes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BackupManga) Reset() {
	*x = BackupManga{}
	mi := &file_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupManga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupManga) ProtoMessage() {}

func (x *BackupManga) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupManga.ProtoReflect.Descriptor instead.
func (*BackupManga) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{1}
}

func (x *BackupManga) GetSource() int64 {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return 0
}

func (x *BackupManga) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *BackupManga) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *BackupManga) GetArtist() string {
	if x != nil && x.Artist != nil {
		return *x.Artist
	}
	return ""
}

func (x *BackupManga) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

func (x *BackupManga) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *BackupManga) GetGenre() []string {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *BackupManga) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *BackupManga) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

func (x *BackupManga) GetDateAdded() int64 {
	if x != nil && x.DateAdded != nil {
		return *x.DateAdded
	}
	return 0
}

func (x *BackupManga) GetViewer() int32 {
	if x != nil && x.Viewer != nil {
		return *x.Viewer
	}
	return 0
}

func (x *BackupManga) GetChapters() []*BackupChapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

func (x *BackupManga) GetCategories() []int64 {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *BackupManga) GetTracking() []*BackupTracking {
	if x != nil {
		return x.Tracking
	}
	return nil
}

func (x *BackupManga) GetFavorite() bool {
	if x != nil && x.Favorite != nil {
		return *x.Favorite
	}
	return false
}

func (x *BackupManga) GetChapterFlags() int32 {
	if x != nil && x.ChapterFlags != nil {
		return *x.ChapterFlags
	}
	return 0
}

func (x *BackupManga) GetViewerFlags() int32 {
	if x != nil && x.ViewerFlags != nil {
		return *x.ViewerFlags
	}
	return 0
}

func (x *BackupManga) GetHistory() []*BackupHistory {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *BackupManga) GetUpdateStrategy() UpdateStrategy {
	if x != nil && x.UpdateStrategy != nil {
		return *x.UpdateStrategy
	}
	return UpdateStrategy_ALWAYS_UPDATE
}

func (x *BackupManga) GetLastModifiedAt() int64 {
	if x != nil && x.LastModifiedAt != nil {
		return *x.LastModifiedAt
	}
	return 0
}

func (x *BackupManga) GetFavoriteModifiedAt() int64 {
	if x != nil && x.FavoriteModifiedAt != nil {
		return *x.FavoriteModifiedAt
	}
	return 0
}

func (x *BackupManga) GetExcludedScanlators() []string {
	if x != nil {
		return x.ExcludedScanlators
	}
	return nil
}

func (x *BackupManga) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *BackupManga) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

// A single chapter.
type BackupChapter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Url            *string                `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	Name           *string                `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Scanlator      *string                `protobuf:"bytes,3,opt,name=scanlator" json:"scanlator,omitempty"`
	Read           *bool                  `protobuf:"varint,4,opt,name=read" json:"read,omitempty"`
	Bookmark       *bool                  `protobuf:"varint,5,opt,name=bookmark" json:"bookmark,omitempty"`
	LastPageRead   *int64                 `protobuf:"varint,6,opt,name=last_page_read,json=lastPageRead" json:"last_page_read,omitempty"`
	DateFetch      *int64                 `protobuf:"varint,7,opt,name=date_fetch,json=dateFetch" json:"date_fetch,omitempty"`
	DateUpload     *int64                 `protobuf:"varint,8,opt,name=date_upload,json=dateUpload" json:"date_upload,omitempty"`
	ChapterNumber  *float32               `protobuf:"fixed32,9,opt,name=chapter_number,json=chapterNumber" json:"chapter_number,omitempty"`
	SourceOrder    *int64                 `protobuf:"varint,10,opt,name=source_order,json=sourceOrder" json:"source_order,omitempty"`
	LastModifiedAt *int64                 `protobuf:"varint,11,opt,name=last_modified_at,json=lastModifiedAt" json:"last_modified_at,omitempty"`
	Version        *int64                 `protobuf:"varint,12,opt,name=version" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BackupChapter) Reset() {
	*x = BackupChapter{}
	mi := &file_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupChapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupChapter) ProtoMessage() {}

func (x *BackupChapter) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupChapter.ProtoReflect.Descriptor instead.
func (*BackupChapter) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{2}
}

func (x *BackupChapter) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *BackupChapter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *BackupChapter) GetScanlator() string {
	if x != nil && x.Scanlator != nil {
		return *x.Scanlator
	}
	return ""
}

func (x *BackupChapter) GetRead() bool {
	if x != nil && x.Read != nil {
		return *x.Read
	}
	return false
}

func (x *BackupChapter) GetBookmark() bool {
	if x != nil && x.Bookmark != nil {
		return *x.Bookmark
	}
	return false
}

func (x *BackupChapter) GetLastPageRead() int64 {
	if x != nil && x.LastPageRead != nil {
		return *x.LastPageRead
	}
	return 0
}

func (x *BackupChapter) GetDateFetch() int64 {
	if x != nil && x.DateFetch != nil {
		return *x.DateFetch
	}
	return 0
}

func (x *BackupChapter) GetDateUpload() int64 {
	if x != nil && x.DateUpload != nil {
		return *x.DateUpload
	}
	return 0
}

func (x *BackupChapter) GetChapterNumber() float32 {
	if x != nil && x.ChapterNumber != nil {
		return *x.ChapterNumber
	}
	return 0
}

func (x *BackupChapter) GetSourceOrder() int64 {
	if x != nil && x.SourceOrder != nil {
		return *x.SourceOrder
	}
	return 0
}

func (x *BackupChapter) GetLastModifiedAt() int64 {
	if x != nil && x.LastModifiedAt != nil {
		return *x.LastModifiedAt
	}
	return 0
}

func (x *BackupChapter) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

// A library category.
type BackupCategory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Order *int64                 `protobuf:"varint,2,opt,name=order" json:"order,omitempty"`
	Id    *int64                 `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
	// Values not in 1.x (bumped by 100)
	Flags         *int64 `protobuf:"varint,100,opt,name=flags" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupCategory) Reset() {
	*x = BackupCategory{}
	mi := &file_backup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupCategory) ProtoMessage() {}

func (x *BackupCategory) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupCategory.ProtoReflect.Descriptor instead.
func (*BackupCategory) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{3}
}

func (x *BackupCategory) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *BackupCategory) GetOrder() int64 {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return 0
}

func (x *BackupCategory) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *BackupCategory) GetFlags() int64 {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return 0
}

// A tracker entry.
type BackupTracking struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SyncId              *int32                 `protobuf:"varint,1,req,name=sync_id,json=syncId" json:"sync_id,omitempty"`
	LibraryId           *int64                 `protobuf:"varint,2,req,name=library_id,json=libraryId" json:"library_id,omitempty"`
	MediaIdInt          *int32                 `protobuf:"varint,3,opt,name=media_id_int,json=mediaIdInt" json:"media_id_int,omitempty"` // deprecated, use media_id
	TrackingUrl         *string                `protobuf:"bytes,4,opt,name=tracking_url,json=trackingUrl" json:"tracking_url,omitempty"`
	Title               *string                `protobuf:"bytes,5,opt,name=title" json:"title,omitempty"`
	LastChapterRead     *float32               `protobuf:"fixed32,6,opt,name=last_chapter_read,json=lastChapterRead" json:"last_chapter_read,omitempty"`
	TotalChapters       *int32                 `protobuf:"varint,7,opt,name=total_chapters,json=totalChapters" json:"total_chapters,omitempty"`
	Score               *float32               `protobuf:"fixed32,8,opt,name=score" json:"score,omitempty"`
	Status              *int32                 `protobuf:"varint,9,opt,name=status" json:"status,omitempty"`
	StartedReadingDate  *int64                 `protobuf:"varint,10,opt,name=started_reading_date,json=startedReadingDate" json:"started_reading_date,omitempty"`
	FinishedReadingDate *int64                 `protobuf:"varint,11,opt,name=finished_reading_date,json=finishedReadingDate" json:"finished_reading_date,omitempty"`
	Private             *bool                  `protobuf:"varint,12,opt,name=private" json:"private,omitempty"`
	MediaId             *int64                 `protobuf:"varint,100,opt,name=media_id,json=mediaId" json:"media_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BackupTracking) Reset() {
	*x = BackupTracking{}
	mi := &file_backup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupTracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupTracking) ProtoMessage() {}

func (x *BackupTracking) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupTracking.ProtoReflect.Descriptor instead.
func (*BackupTracking) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{4}
}

func (x *BackupTracking) GetSyncId() int32 {
	if x != nil && x.SyncId != nil {
		return *x.SyncId
	}
	return 0
}

func (x *BackupTracking) GetLibraryId() int64 {
	if x != nil && x.LibraryId != nil {
		return *x.LibraryId
	}
	return 0
}

func (x *BackupTracking) GetMediaIdInt() int32 {
	if x != nil && x.MediaIdInt != nil {
		return *x.MediaIdInt
	}
	return 0
}

func (x *BackupTracking) GetTrackingUrl() string {
	if x != nil && x.TrackingUrl != nil {
		return *x.TrackingUrl
	}
	return ""
}

func (x *BackupTracking) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *BackupTracking) GetLastChapterRead() float32 {
	if x != nil && x.LastChapterRead != nil {
		return *x.LastChapterRead
	}
	return 0
}

func (x *BackupTracking) GetTotalChapters() int32 {
	if x != nil && x.TotalChapters != nil {
		return *x.TotalChapters
	}
	return 0
}

func (x *BackupTracking) GetScore() float32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *BackupTracking) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *BackupTracking) GetStartedReadingDate() int64 {
	if x != nil && x.StartedReadingDate != nil {
		return *x.StartedReadingDate
	}
	return 0
}

func (x *BackupTracking) GetFinishedReadingDate() int64 {
	if x != nil && x.FinishedReadingDate != nil {
		return *x.FinishedReadingDate
	}
	return 0
}

func (x *BackupTracking) GetPrivate() bool {
	if x != nil && x.Private != nil {
		return *x.Private
	}
	return false
}

func (x *BackupTracking) GetMediaId() int64 {
	if x != nil && x.MediaId != nil {
		return *x.MediaId
	}
	return 0
}

// Reading history for a chapter.
type BackupHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *string                `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	LastRead      *int64                 `protobuf:"varint,2,req,name=last_read,json=lastRead" json:"last_read,omitempty"`
	ReadDuration  *int64                 `protobuf:"varint,3,opt,name=read_duration,json=readDuration" json:"read_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupHistory) Reset() {
	*x = BackupHistory{}
	mi := &file_backup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupHistory) ProtoMessage() {}

func (x *BackupHistory) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupHistory.ProtoReflect.Descriptor instead.
func (*BackupHistory) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{5}
}

func (x *BackupHistory) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *BackupHistory) GetLastRead() int64 {
	if x != nil && x.LastRead != nil {
		return *x.LastRead
	}
	return 0
}

func (x *BackupHistory) GetReadDuration() int64 {
	if x != nil && x.ReadDuration != nil {
		return *x.ReadDuration
	}
	return 0
}

// A source mapping (source ID → name).
type BackupSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	SourceId      *int64                 `protobuf:"varint,2,req,name=source_id,json=sourceId" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupSource) Reset() {
	*x = BackupSource{}
	mi := &file_backup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSource) ProtoMessage() {}

func (x *BackupSource) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSource.ProtoReflect.Descriptor instead.
func (*BackupSource) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{6}
}

func (x *BackupSource) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *BackupSource) GetSourceId() int64 {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return 0
}

// App or source preferences.
type BackupPreference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value         *PreferenceValue       `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupPreference) Reset() {
	*x = BackupPreference{}
	mi := &file_backup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupPreference) ProtoMessage() {}

func (x *BackupPreference) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupPreference.ProtoReflect.Descriptor instead.
func (*BackupPreference) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{7}
}

func (x *BackupPreference) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *BackupPreference) GetValue() *PreferenceValue {
	if x != nil {
		return x.Value
	}
	return nil
}

// Source-specific preferences.
type BackupSourcePreferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceKey     *string                `protobuf:"bytes,1,req,name=source_key,json=sourceKey" json:"source_key,omitempty"`
	Prefs         []*BackupPreference    `protobuf:"bytes,2,rep,name=prefs" json:"prefs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupSourcePreferences) Reset() {
	*x = BackupSourcePreferences{}
	mi := &file_backup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSourcePreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSourcePreferences) ProtoMessage() {}

func (x *BackupSourcePreferences) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSourcePreferences.ProtoReflect.Descriptor instead.
func (*BackupSourcePreferences) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{8}
}

func (x *BackupSourcePreferences) GetSourceKey() string {
	if x != nil && x.SourceKey != nil {
		return *x.SourceKey
	}
	return ""
}

func (x *BackupSourcePreferences) GetPrefs() []*BackupPreference {
	if x != nil {
		return x.Prefs
	}
	return nil
}

// Preference value - using type discriminator matching kotlinx.serialization.
type PreferenceValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Truevalue     []byte                 `protobuf:"bytes,2,req,name=truevalue" json:"truevalue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreferenceValue) Reset() {
	*x = PreferenceValue{}
	mi := &file_backup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferenceValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferenceValue) ProtoMessage() {}

func (x *PreferenceValue) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreferenceValue.ProtoReflect.Descriptor instead.
func (*PreferenceValue) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{9}
}

func (x *PreferenceValue) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *PreferenceValue) GetTruevalue() []byte {
	if x != nil {
		return x.Truevalue
	}
	return nil
}

var File_backup_proto protoreflect.FileDescriptor

const file_backup_proto_rawDesc = "" +
	"\n" +
	"\fbackup.proto\x12\atachibk\"\xed\x02\n" +
	"\x06Backup\x127\n" +
	"\fbackup_manga\x18\x01 \x03(\v2\x14.tachibk.BackupMangaR\vbackupManga\x12D\n" +
	"\x11backup_categories\x18\x02 \x03(\v2\x17.tachibk.BackupCategoryR\x10backupCategories\x12<\n" +
	"\x0ebackup_sources\x18e \x03(\v2\x15.tachibk.BackupSourceR\rbackupSources\x12H\n" +
	"\x12backup_preferences\x18h \x03(\v2\x19.tachibk.BackupPreferenceR\x11backupPreferences\x12\\\n" +
	"\x19backup_source_preferences\x18i \x03(\v2 .tachibk.BackupSourcePreferencesR\x17backupSourcePreferences\"\xc7\x06\n" +
	"\vBackupManga\x12\x16\n" +
	"\x06source\x18\x01 \x02(\x03R\x06source\x12\x10\n" +
	"\x03url\x18\x02 \x02(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x04 \x01(\tR\x06artist\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x14\n" +
	"\x05genre\x18\a \x03(\tR\x05genre\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12#\n" +
	"\rthumbnail_url\x18\t \x01(\tR\fthumbnailUrl\x12\x1d\n" +
	"\n" +
	"date_added\x18\r \x01(\x03R\tdateAdded\x12\x16\n" +
	"\x06viewer\x18\x0e \x01(\x05R\x06viewer\x122\n" +
	"\bchapters\x18\x10 \x03(\v2\x16.tachibk.BackupChapterR\bchapters\x12\x1e\n" +
	"\n" +
	"categories\x18\x11 \x03(\x03R\n" +
	"categories\x123\n" +
	"\btracking\x18\x12 \x03(\v2\x17.tachibk.BackupTrackingR\btracking\x12\x1a\n" +
	"\bfavorite\x18d \x01(\bR\bfavorite\x12#\n" +
	"\rchapter_flags\x18e \x01(\x05R\fchapterFlags\x12!\n" +
	"\fviewer_flags\x18g \x01(\x05R\vviewerFlags\x120\n" +
	"\ahistory\x18h \x03(\v2\x16.tachibk.BackupHistoryR\ahistory\x12@\n" +
	"\x0fupdate_strategy\x18i \x01(\x0e2\x17.tachibk.UpdateStrategyR\x0eupdateStrategy\x12(\n" +
	"\x10last_modified_at\x18j \x01(\x03R\x0elastModifiedAt\x120\n" +
	"\x14favorite_modified_at\x18k \x01(\x03R\x12favoriteModifiedAt\x12/\n" +
	"\x13excluded_scanlators\x18l \x03(\tR\x12excludedScanlators\x12\x18\n" +
	"\aversion\x18m \x01(\x03R\aversion\x12\x14\n" +
	"\x05notes\x18n \x01(\tR\x05notes\"\xf7\x02\n" +
	"\rBackupChapter\x12\x10\n" +
	"\x03url\x18\x01 \x02(\tR\x03url\x12\x12\n" +
	"\x04name\x18\x02 \x02(\tR\x04name\x12\x1c\n" +
	"\tscanlator\x18\x03 \x01(\tR\tscanlator\x12\x12\n" +
	"\x04read\x18\x04 \x01(\bR\x04read\x12\x1a\n" +
	"\bbookmark\x18\x05 \x01(\bR\bbookmark\x12$\n" +
	"\x0elast_page_read\x18\x06 \x01(\x03R\flastPageRead\x12\x1d\n" +
	"\n" +
	"date_fetch\x18\a \x01(\x03R\tdateFetch\x12\x1f\n" +
	"\vdate_upload\x18\b \x01(\x03R\n" +
	"dateUpload\x12%\n" +
	"\x0echapter_number\x18\t \x01(\x02R\rchapterNumber\x12!\n" +
	"\fsource_order\x18\n" +
	" \x01(\x03R\vsourceOrder\x12(\n" +
	"\x10last_modified_at\x18\v \x01(\x03R\x0elastModifiedAt\x12\x18\n" +
	"\aversion\x18\f \x01(\x03R\aversion\"`\n" +
	"\x0eBackupCategory\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12\x14\n" +
	"\x05order\x18\x02 \x01(\x03R\x05order\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x14\n" +
	"\x05flags\x18d \x01(\x03R\x05flags\"\xbf\x03\n" +
	"\x0eBackupTracking\x12\x17\n" +
	"\async_id\x18\x01 \x02(\x05R\x06syncId\x12\x1d\n" +
	"\n" +
	"library_id\x18\x02 \x02(\x03R\tlibraryId\x12 \n" +
	"\fmedia_id_int\x18\x03 \x01(\x05R\n" +
	"mediaIdInt\x12!\n" +
	"\ftracking_url\x18\x04 \x01(\tR\vtrackingUrl\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12*\n" +
	"\x11last_chapter_read\x18\x06 \x01(\x02R\x0flastChapterRead\x12%\n" +
	"\x0etotal_chapters\x18\a \x01(\x05R\rtotalChapters\x12\x14\n" +
	"\x05score\x18\b \x01(\x02R\x05score\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x120\n" +
	"\x14started_reading_date\x18\n" +
	" \x01(\x03R\x12startedReadingDate\x122\n" +
	"\x15finished_reading_date\x18\v \x01(\x03R\x13finishedReadingDate\x12\x18\n" +
	"\aprivate\x18\f \x01(\bR\aprivate\x12\x19\n" +
	"\bmedia_id\x18d \x01(\x03R\amediaId\"c\n" +
	"\rBackupHistory\x12\x10\n" +
	"\x03url\x18\x01 \x02(\tR\x03url\x12\x1b\n" +
	"\tlast_read\x18\x02 \x02(\x03R\blastRead\x12#\n" +
	"\rread_duration\x18\x03 \x01(\x03R\freadDuration\"?\n" +
	"\fBackupSource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tsource_id\x18\x02 \x02(\x03R\bsourceId\"T\n" +
	"\x10BackupPreference\x12\x10\n" +
	"\x03key\x18\x01 \x02(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x02(\v2\x18.tachibk.PreferenceValueR\x05value\"i\n" +
	"\x17BackupSourcePreferences\x12\x1d\n" +
	"\n" +
	"source_key\x18\x01 \x02(\tR\tsourceKey\x12/\n" +
	"\x05prefs\x18\x02 \x03(\v2\x19.tachibk.BackupPreferenceR\x05prefs\"C\n" +
	"\x0fPreferenceValue\x12\x12\n" +
	"\x04type\x18\x01 \x02(\tR\x04type\x12\x1c\n" +
	"\ttruevalue\x18\x02 \x02(\fR\ttruevalue*8\n" +
	"\x0eUpdateStrategy\x12\x11\n" +
	"\rALWAYS_UPDATE\x10\x00\x12\x13\n" +
	"\x0fONLY_FETCH_ONCE\x10\x01B7Z5github.com/misfit/mangastu/internal/format/tachibk/pb"

var (
	file_backup_proto_rawDescOnce sync.Once
	file_backup_proto_rawDescData []byte
)

func file_backup_proto_rawDescGZIP() []byte {
	file_backup_proto_rawDescOnce.Do(func() {
		file_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backup_proto_rawDesc), len(file_backup_proto_rawDesc)))
	})
	return file_backup_proto_rawDescData
}

var file_backup_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_backup_proto_goTypes = []any{
	(UpdateStrategy)(0),             // 0: tachibk.UpdateStrategy
	(*Backup)(nil),                  // 1: tachibk.Backup
	(*BackupManga)(nil),             // 2: tachibk.BackupManga
	(*BackupChapter)(nil),           // 3: tachibk.BackupChapter
	(*BackupCategory)(nil),          // 4: tachibk.BackupCategory
	(*BackupTracking)(nil),          // 5: tachibk.BackupTracking
	(*BackupHistory)(nil),           // 6: tachibk.BackupHistory
	(*BackupSource)(nil),            // 7: tachibk.BackupSource
	(*BackupPreference)(nil),        // 8: tachibk.BackupPreference
	(*BackupSourcePreferences)(nil), // 9: tachibk.BackupSourcePreferences
	(*PreferenceValue)(nil),         // 10: tachibk.PreferenceValue
}
var file_backup_proto_depIdxs = []int32{
	2,  // 0: tachibk.Backup.backup_manga:type_name -> tachibk.BackupManga
	4,  // 1: tachibk.Backup.backup_categories:type_name -> tachibk.BackupCategory
	7,  // 2: tachibk.Backup.backup_sources:type_name -> tachibk.BackupSource
	8,  // 3: tachibk.Backup.backup_preferences:type_name -> tachibk.BackupPreference
	9,  // 4: tachibk.Backup.backup_source_preferences:type_name -> tachibk.BackupSourcePreferences
	3,  // 5: tachibk.BackupManga.chapters:type_name -> tachibk.BackupChapter
	5,  // 6: tachibk.BackupManga.tracking:type_name -> tachibk.BackupTracking
	6,  // 7: tachibk.BackupManga.history:type_name -> tachibk.BackupHistory
	0,  // 8: tachibk.BackupManga.update_strategy:type_name -> tachibk.UpdateStrategy
	10, // 9: tachibk.BackupPreference.value:type_name -> tachibk.PreferenceValue
	8,  // 10: tachibk.BackupSourcePreferences.prefs:type_name -> tachibk.BackupPreference
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_backup_proto_init() }
func file_backup_proto_init() {
	if File_backup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backup_proto_rawDesc), len(file_backup_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backup_proto_goTypes,
		DependencyIndexes: file_backup_proto_depIdxs,
		EnumInfos:         file_backup_proto_enumTypes,
		MessageInfos:      file_backup_proto_msgTypes,
	}.Build()
	File_backup_proto = out.File
	file_backup_proto_goTypes = nil
	file_backup_proto_depIdxs = nil
}
